//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_SkalochkinFedor_ISP321_MasterPol.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.PartnersImport = new HashSet<PartnersImport>();
        }
    
        public int IDAddress { get; set; }
        public int PostIndex { get; set; }
        public int Region { get; set; }
        public int City { get; set; }
        public int Street { get; set; }
        public int House { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual PostIndex PostIndex1 { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Street Street1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnersImport> PartnersImport { get; set; }
    }
}
