//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_SkalochkinFedor_ISP321_MasterPol.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTypeImport
    {
        public int IDTypeMaterial { get; set; }
        public string TypeMaterial { get; set; }
        public double PercentageDeffect { get; set; }
    }
}
