//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_SkalochkinFedor_ISP321_MasterPol.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductsImport
    {
        public int IDProducts { get; set; }
        public int Products { get; set; }
        public int TitlePartner { get; set; }
        public int QuantityProducts { get; set; }
        public System.DateTime DateSale { get; set; }
    
        public virtual PartnerTitle PartnerTitle { get; set; }
        public virtual TitleProducts TitleProducts { get; set; }
    }
}
