//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_SkalochkinFedor_ISP321_MasterPol.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImport
    {
        public int IDProducts { get; set; }
        public int ProductsType { get; set; }
        public int ProductsTitle { get; set; }
        public int Article { get; set; }
        public double MinPrice { get; set; }
    
        public virtual PartnerTitle PartnerTitle { get; set; }
        public virtual ProductTypeImport ProductTypeImport { get; set; }
    }
}
